apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiadventure.fullname" . }}
  labels:
    app: {{ include "aiadventure.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aiadventure.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "aiadventure.fullname" . }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ include "aiadventure.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
