apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "microservice.fullname" . }}
data:
{{- range $k, $v := .Values.env.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}

