replicaCount: 2

image:
  repository: ghcr.io/temitayocharles/fintech-transaction-service
  tag: "latest"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

containerPort: 8082

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  config:
    KAFKA_BROKERS: "kafka:9092"
    ENVIRONMENT: "development"
    PORT: "8082"

secrets:
  - envName: DATABASE_URL
    secretName: transaction-db-secret
    secretKey: DATABASE_URL
externalSecrets:
  enabled: true
  storeRef: vault-backend
  refreshInterval: 1m
  basePath: fintech/dev/transaction-service

