apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fintech.fullname" . }}-config
  labels:
    app: {{ include "fintech.fullname" . }}
data:
{{- range $key, $val := .Values.env.config }}
  {{ $key }}: "{{ $val }}"
{{- end }}
