replicaCount: 2

image:
  repository: ghcr.io/temitayocharles/fintech-account-service
  tag: "latest"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

containerPort: 8081

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  config:
    KAFKA_BROKERS: "kafka:9092"
    ENVIRONMENT: "development"
    PORT: "8081"

secrets:
  - envName: DATABASE_URL
    secretName: account-db-secret
    secretKey: DATABASE_URL
  - envName: ENCRYPTION_KEY
    secretName: account-encryption-key
    secretKey: ENCRYPTION_KEY
externalSecrets:
  enabled: true
  storeRef: vault-backend
  refreshInterval: 1m
  basePath: fintech/dev/account-service

