{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (printf "%s-config" (include "microservice.fullname" .)) .Values.configMap.name }}
  labels:
    app.kubernetes.io/name: {{ include "microservice.fullname" . }}
data:
{{- range $k, $v := .Values.env.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
