apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fintech.fullname" . }}
  labels:
    app: {{ include "fintech.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fintech.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "fintech.fullname" . }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ include "fintech.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "fintech.fullname" . }}-config
{{- if .Values.secrets }}
          env:
{{- range .Values.secrets }}
            - name: {{ .envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
{{- end }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
